### ISSUE TITLE
Initially launching the project fails.

### ISSUE THREAD

**Issue by tgoyer** [AndrewBanks10/create-react-cr-project#1]
**Repro Steps:**
From terminal in project folder, run: `./node_modules/.bin/create-react-cr-project`

**Output**
`Copy project files.`
`Installing required libraries with npm.`
`This will take some time.....`
`npm install error: Error: spawn npm.cmd ENOENT.`

**Expected**
It works.  :)

**Work around:**

- Manually run `npm install` after npm installing `create-react-cr-project`
- After npm install is done, re-run `./node_modules/.bin/create-react-cr-project` 

**Additional Info**
OS: MacOSX, v10.13.3
`npm -v` -> 5.8.0
`node -v` -> v8.9.1

**Comment by AndrewBanks10** [comment]
Resolved.

Only affected Macs.

**Comment by tgoyer** [comment]
Thanks for the quick turn around!  👍

**Comment by AndrewBanks10** [comment]
Tim,

Feel free to ask questions.

That project is super cool.

Andrew
